@startuml use-cases

left to right direction

' actors

:user: as us
:student: as st
:instructor: as tr

us <|-- st
us <|-- tr

' use cases

(login) as (UC1)
(list courses) as (UC2)
(open lecture content) as (UC3)
(submit questions) as (UC4)
(manage courses) as (UC5)
(list questions) as (UC6)
(answer questions) as (UC7)

' user use cases

us --> UC1
us --> UC2

' student use cases

st --> UC3
st --> UC4

' trainer use cases

tr --> UC5
tr --> UC6
tr --> UC7

@enduml